services:
  - type: web
    name: fintech-gastos-challenge
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Fintech Gastos Challenge
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://fintech-gastos-challenge.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: fintech-gastos-db
          property: connectionString
      - key: MAIL_MAILER
        value: log

databases:
  - name: fintech-gastos-db
    plan: basic-256mb
    databaseName: fintech_gastos
    user: fintech_gastos