services:
  - type: web
    name: fintech-gastos-challenge
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Fintech Gastos Challenge
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:vmwYPbtF8WJyrg5WHRRmkqnsIxN5NYyAd3Teqiagjs8=
      - key: APP_URL
        value: https://fintech-gastos-challenge.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: MAIL_MAILER
        value: log
